version: '3.8'

services:
  pg-email-db:
    image: postgres:latest
    container_name: email-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ms-email
    ports:
      - "5432:5432"

  pg-job-db:
    image: postgres:latest
    container_name: job-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ms-job
    ports:
      - "5430:5430"

  email-service:
    build:
      context: ./email
      dockerfile: Dockerfile
    volumes:
      - ./email/target:/tmp
    ports:
      - "8082:8082"
    depends_on:
      - pg-email-db

  job-service:
    build:
      context: ./job
      dockerfile: Dockerfile
    volumes:
      - ./job/target:/tmp
    ports:
      - "8081:8081"
    depends_on:
      - pg-job-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://job-db:5432/ms-job
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
